Update i18n.js
mxwell/aspan-trainer pull request #2
Opened 2024-02-01 16:21 UTC by MuratKaribai

2024-02-01 16:32 UTC, mxwell requested changes

2024-02-01 16:32 UTC, mxwell commented on static/src/javascripts/lib/i18n.js
> +    setEnRuKZ(map, "chooseVerbExceptionOrNot",
K**z**

2024-02-01 18:07 UTC, mxwell commented on static/src/javascripts/lib/i18n.js
> +        "Уикисіөздіктегі аудармасы",
Уикис**і**өздіктегі

2024-02-02 08:44 UTC, MuratKaribai commented on static/src/javascripts/lib/i18n.js
> +        "Уикисіөздіктегі аудармасы",
Уикисөздіктегі

2024-02-02 17:15 UTC, merged